services:
  - type: web
    name: strapi-agency-website-api
    env: node
    region: oregon
    plan: free
    rootDir: strapi-cms
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL
        value: true
      - key: APP_KEYS
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: API_TOKEN_SALT
        sync: false
      - key: TRANSFER_TOKEN_SALT
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: strapi-agency-website-frontend
    env: static
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_STRAPI_URL
        sync: false